name: dart_frog_example
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.1.0
  logger: ^2.0.2+1
  shelf_cors_headers: ^0.1.5
  eventsource: ^0.4.0
  stream_channel: ^2.1.2
  image: ^4.1.7
  mime: ^1.0.5

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
