name: dart_frog_example
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.0.1
  logger: ^2.0.2+1
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.1
  very_good_analysis: ^5.1.0
