name: flutter_web
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  http: ^1.1.0
  riverpod: ^2.4.4
  flutter_riverpod: ^2.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Santana
      fonts:
        - asset: assets/fonts/Santana.ttf
          weight: 300
        - asset: assets/fonts/Santana-Bold.ttf
          weight: 700
        - asset: assets/fonts/Santana-Black.ttf
          weight: 900
        - asset: assets/fonts/Santana-Black.ttf
          weight: 500

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
