name: mockdash
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.0
  faker_dart: ^0.2.1
  path: ^1.8.3
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  watcher: ^1.1.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
